In [38]:
path = "../data/"

import pandas as pd


files = ["neo4j_nodos_16.csv","neo4j_nodos_20.csv","neo4j_nodos_24.csv"]
years = [int(nombre[-6:-4]) for nombre in files]

list_df =  [pd.read_csv(path+nombre).dropna() for nombre in files]
for i,df in enumerate(list_df):
    df["year"] = years[i]
df = pd.concat(list_df)
df

,userid,screen,created_at,common_degree,verified,followers,following,nTweets,contagio,sent,tipo,year
2,27290233,Macs_Wax,2009-03-28T19:23:31.000Z,66.0,False,2204,2680,2,COMMON,contagio,REP,16
4,713399133915230208,jeaniefacts,2016-03-25T16:16:22.000Z,0.0,False,161,244,50,majority,contagio,REP,16
17,760084617336655872,kiser_stan,2016-08-01T12:07:49.000Z,57.0,False,13,104,6,COMMON,contagio,REP,16
19,335867587,Felix_Nuno,2011-07-15T11:16:14.000Z,1.0,False,453,759,1,COMMON,contagio,DEM,16
21,209771034,Chenagrrl,2010-10-29T22:09:42.000Z,18.0,False,977,2125,15,COMMON,contagio,DEM,16
...,...,...,...,...,...,...,...,...,...,...,...,...
2168,1739120821,newkirk_trevor,2013-09-07T01:17:38.000Z,5.0,False,305,112,1,COMMON,contagio,REP,24
2169,21430206,terip64,2009-02-20T20:27:06.000Z,209.0,False,31,187,6,COMMON,contagio,DEM,24
2171,3207488584,applefan418,2015-04-25T20:20:39.000Z,1.0,False,21,165,1,COMMON,contagio,DEM,24
2172,39671081,NCCaniac42,2009-05-13T02:53:03.000Z,190.0,False,1079,2119,5,COMMON,contagio,DEM,24
2174,965299622,brianglenntv,2012-11-23T01:43:11.000Z,2.0,False,1983,1001,7,COMMON,contagio,REP,24

In [42]:
df.contagio.value_counts()

contagio
COMMON      4991
majority      55
SIMILAR       53
Name: count, dtype: int64

In [55]:
df2 = df.groupby('contagio', group_keys=False).sample(n=50)

In [57]:
df2.contagio.value_counts()

contagio
COMMON      50
SIMILAR     50
majority    50
Name: count, dtype: int64

In [59]:
df2.tipo.value_counts()

tipo
DEM    77
REP    73
Name: count, dtype: int64

In [61]:
df2.to_csv(path+"muestra_contagio.csv",index=False)